In [1]:
import numpy as np
np.__version__

'1.14.2'

**2.1 理解Python中的数据类型**

2.1.1 Python整型不仅仅是一个整型

2.1.2 Python列表不仅仅是一个列表

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [10]:
L3 = [True, '2', 3.0, 5]
[type(item) for item in L3]

[bool, str, float, int]

2.1.3 Python中的固定类型数组

In [12]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.1.4 从Python列表创建数组

In [13]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [15]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [16]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
# 嵌套列表构成的多维数组
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

2.1.5 从头创建数组

In [18]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# 创建一个3×5的浮点型数组，数组的值都是1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# 创建一个3×5的浮点型数组，数组的值都是3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# 创建一个2×5的浮点型数组，数组的值是一个线性序列
# 从0开始，到20结束，步长为2
# （它和内置的range()函数类型）
np.arange(0, 20, 2).reshape((2, 5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [24]:
# 创建一个5个元素的数组，这5个数均匀地分配到0-1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# 创建一个3×3的、在0~1均匀分布的随机组成的数组
np.random.random((3, 3))

array([[0.83601611, 0.84861445, 0.09785659],
       [0.12507279, 0.37423006, 0.83207508],
       [0.97709064, 0.59057947, 0.37657307]])

In [26]:
# 创建一个3×3的、均值为0， 方差为1的正态分布的随机数组
np.random.normal(0, 1, (3, 3))

array([[ 1.13260445, -0.96343712,  1.4082184 ],
       [ 0.03235183,  0.38465595,  0.63868272],
       [ 0.87028665, -0.28296922, -1.73287172]])

In [27]:
# 创建一个3×3的、[0, 10)区间的随机整型数组
np.random.randint(0, 10, (3, 3))

array([[5, 7, 4],
       [1, 2, 6],
       [4, 4, 4]])

In [28]:
# 创建一个3×3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# 创建一个由3个整型数组成的未初始化的数组
# 数组的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

2.1.6 Numpy标准数据类型

**2.2 Numpy数组基础**

2.2.1 Numpy数组的属性

In [32]:
import numpy as np
np.random.seed(0) # 设置随机数种子
x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

In [36]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [37]:
print("dtype:", x3.dtype)

dtype: int32


In [38]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


2.2.2 数组索引：获取单个元素

In [39]:
x1

array([5, 0, 3, 3, 7, 9])

In [40]:
x1[0]

5

In [41]:
x1[4]

7

In [42]:
x1[-1]

9

In [43]:
x1[-2]

7

In [44]:
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [45]:
x2[0, 0]

4

In [46]:
x2[2, 0]

5

In [47]:
x2[2, -1]

1

In [49]:
x2[0, 0] = 12
x2

array([[12,  3,  4,  4],
       [ 8,  4,  3,  7],
       [ 5,  5,  0,  1]])

In [51]:
x1[0] = 3.14159 # 数组是固定类型，浮点值被截断成整型
x1

array([3, 0, 3, 3, 7, 9])

2.2.3 数组切片：获取子数组

1. 一维子数组

In [54]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[:5] # 前五个元素

array([0, 1, 2, 3, 4])

In [56]:
x[5:] # 索引五之后的元素

array([5, 6, 7, 8, 9])

In [57]:
x[4:7] # 中间的子数组

array([4, 5, 6])

In [58]:
x[::2] # 每隔一个元素

array([0, 2, 4, 6, 8])

In [59]:
x[1::2] # 每隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [60]:
# 若步长为负值，start参数和stop参数默认是被交换的
x[::-1] # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

In [70]:
x[-1:3:-2]

array([9, 7, 5])

In [71]:
x[0:-3:-2]

array([], dtype=int32)

In [72]:
x[0:1:-1]

array([], dtype=int32)

In [73]:
x[-4:1:-2]

array([6, 4, 2])

In [74]:
x[-4:1:-1]

array([6, 5, 4, 3, 2])

2. 多维子数组

In [75]:
x2

array([[12,  3,  4,  4],
       [ 8,  4,  3,  7],
       [ 5,  5,  0,  1]])

In [76]:
x2[:2, :3] # 两行，三列

array([[12,  3,  4],
       [ 8,  4,  3]])

In [77]:
x2[:3, ::2] # 三行，每隔一列

array([[12,  4],
       [ 8,  3],
       [ 5,  0]])

In [78]:
x2[::-1, ::-1]

array([[ 1,  0,  5,  5],
       [ 7,  3,  4,  8],
       [ 4,  4,  3, 12]])

3. 获取数组的行和列

In [79]:
print(x2[:, 0]) # x2的第一列

[12  8  5]


In [80]:
print(x2[0, :]) # x2的第一行

[12  3  4  4]


In [81]:
print(x2[0]) # 等同x2[0, :]

[12  3  4  4]


4. 非副本视图的子数组

In [82]:
print(x2)

[[12  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


In [83]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  3]
 [ 8  4]]


In [84]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  3]
 [ 8  4]]


In [85]:
print(x2)

[[99  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


5. 创建数组的副本

In [86]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  3]
 [ 8  4]]


In [87]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  3]
 [ 8  4]]


In [88]:
print(x2)

[[99  3  4  4]
 [ 8  4  3  7]
 [ 5  5  0  1]]


2.2.4 数组的变形

In [90]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
x = np.array([1, 2, 3])

# 通过变形获得的行向量
x.reshape((1, 3))

array([[1, 2, 3]])

In [92]:
# 通过newaxis获得的行向量
x[np.newaxis, :]

array([[1, 2, 3]])

In [93]:
# 通过变形获得的列向量
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [94]:
# 通过newaxis获得的列向量
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

2.2.5 数组拼接和分裂

1. 数组的拼接

In [97]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [98]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [99]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [100]:
# 沿着第一个轴拼接
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [101]:
# 沿着第二个轴拼接（从0开始索引）
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [102]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# 垂直栈数组
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [103]:
# 水平栈数组
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

2. 数组的分裂

In [105]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [106]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [108]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**2.3 Numpy数组的计算：通用函数**

2.3.1 缓慢的循环

In [109]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [110]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

5 s ± 362 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


2.3.2 通用函数介绍

In [111]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [112]:
%timeit (1.0 / big_array)

11.4 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [115]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [117]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

2.3.3 探索Numpy的通用函数

1. 数组的运算

In [118]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # 整除法

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [119]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [120]:
np.add(x, 2)

array([2, 3, 4, 5])

2. 绝对值

In [121]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [122]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [123]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [124]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j]) # 复数
np.abs(x)

array([5., 5., 2., 1.])

3. 三角函数

In [125]:
theta = np.linspace(0, np.pi, 3)

In [126]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [132]:
x = [-1, 0, 1]
print("x         = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


4. 指数和对数

In [133]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [136]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [137]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
